name: "🐛 Bug Report"
description: Подайте отчёт об ошибке.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчёт об ошибке!
  - type: input
    id: contact
    attributes:
      label: Контактные данные
      description: Как мы можем связаться с вами, если нам нужна дополнительная информация?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 🐞 Что произошло?
      description: Расскажите, чего вы ожидали?
      placeholder: Расскажите, что вы видите!
      value: "Случился баг!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Критичность
      description: Какой уровень критичности по Вашему?
      options:
        - 🔴 Критическая (сервис не работает)
        - 🟠 Высокая (основная функциональность нарушена)
        - 🟡 Средняя (частичная проблема)
        - 🟢 Низкая (косметическая проблема)
      default: 3
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Соответствующий лог вывод
      description: Пожалуйста, скопируйте и вставьте любой соответствующий результат лога. Это будет автоматически отформатировано в код, так что не нужно делать отступы.
      render: shell
  - type: markdown
    attributes:
      value: "Спасибо, что заполнили нашу форму!"
