name: "🚀 Feature Request"
description: Предложите новую функциональность или улучшение
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        📋 Описание фичи
  - type: textarea
    id: what-added
    attributes:
      label: 🎯 Что хотите добавить?
      description: Четко и ясно опишите, что вы хотите добавить или улучшить
      placeholder: Хочу чтобы все!
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Укажите статус значимости для фичи
      options:
        - 🔴 Высокий (критично для проекта)
        - 🟡 Средний (важно, но не срочно)
        - 🟢 Низкий (улучшение качества жизни)
      default: 0
    validations:
      required: true